### ISSUE TITLE
TLS segment is underaligned

### ISSUE THREAD

**Issue by NonXZhu** [Kr328/ClashForMagisk#2]
This is the log.

--------- beginning of system
--------- beginning of main
09-09 22:21:32.295  3107  3226 D Clash   : Control File Changed starter.yaml182043245997
09-09 22:29:59.530  3107  3226 D Clash   : Control File Changed config.yaml
09-09 22:33:21.858  3107  3226 D Clash   : Control File Changed Country.mmdb
09-09 22:33:48.730  3107  3226 D Clash   : Control File Changed START
09-09 22:33:48.972  3107  3226 D Clash   : Starting clash /dev/clash_root/core/setuidgid 1001 1001 3003,1015 /dev/clash_root/core/clash -d /sdcard/Android/data/com.github.kr328.clash 2>&1
09-09 22:33:48.975  3107  3226 I Clash   : Clash started
09-09 22:33:48.992  3107  3226 D Clash   : Control File Changed RUNNING
09-09 22:33:48.999  3107 12912 I Clash   : error: "/dev/clash_root/core/clash": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
--------- beginning of crash
09-09 22:33:49.060  3107  3226 D Clash   : Control File Changed STOPPED

**Comment by Kr328** [comment]
fixed
