### ISSUE TITLE
重启手机后丢失 ‘cfm’ 文件夹

### ISSUE THREAD

**Issue by sambell361** [Kr328/ClashForMagisk#5]
**情况描述：** 有一次我在‘cfm’ RUNNING的情况下重启了手机，手机开机后就发现整个’com.github.kr328.clash‘ 文件夹都没了，当时没排查出哪里的问题，就重新丢入config后继续使用。今天上午手机电量低，自动启动了低电量模式，然后我发现telegram掉线了，进文件管理器发现整个文件夹又没了。
  **环境：** 小米6X，Android 10，Pixel Experience官方包，magisk模块列表：Chinese (Simplified) Font Completion (多字重模块)、Clash for Magisk、Riru-core、Riru-location report enabler、Riru-Storage Redirect.
  **config头部：**
`---
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
redir-port: 7892
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 119.28.28.28
external-controller: 0.0.0.0:9090`

**Comment by Kr328** [comment]
如果是 安装了 clash for android 再卸载
或者使用某种清理软件 清理卸载残留
就会有这样的情况

**Comment by sambell361** [comment]
那么也许是sd maid的锅吧，我经常使用sd maid清理垃圾，但是sd maid好像没有排除文件夹选项啊，如何保护cfm文件夹不被删除呢？

**Comment by Kr328** [comment]
请自行搜索解决方案
本项目不能保证配置不被删除
