### ISSUE TITLE
Can't Start Clash

### ISSUE THREAD

**Issue by Steph2709** [Kr328/ClashForMagisk#6]
I installed Clash for Magisk, but I can't start it. I can find the data directory in `/sdcard/Android/com.github.kr328`. I then try to start it by creating a generic text file with the name `START` in the same directory, however the status file doesn't change. I have tried rebooting but doesn't work. I have a Redmi Note 4 with Helio x20 SOC. Magisk version is 20.3 and the phone runs on an Android 6.0 custom ROM. What should I do?

**Comment by Lzx1085325316** [comment]
I have encountered this problem too, have you solved it?
If you have, could you please tell me how to solve it?
